In [30]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding,Dense
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import tensorflow as tf
from tensorflow import keras

In [23]:
sentences= [
    "The sun sets behind the mountains, casting a golden glow across the valley.",
    "Artificial intelligence is transforming industries by increasing efficiency and innovation.",
    "Reading books can expand your horizons and enhance your understanding of the world.",
    "The gentle sound of rain created a soothing atmosphere on the quiet street.",
    "Traveling to new places allows you to experience diverse cultures and traditions.",
    "Music has the power to evoke emotions and connect people from different backgrounds.",
    "A healthy diet and regular exercise are essential for maintaining overall well-being.",
    "Technology is rapidly evolving, shaping the way we communicate and interact.",
    "Friendship is built on trust, understanding, and shared experiences.",
    "The intricate patterns of nature inspire artists and scientists alike."
]

In [24]:
# Define the vocabulary size
vocab_size=200

In [25]:
# One Hot Representation
one_hot_repr=[one_hot(words,vocab_size)for words in sentences]
one_hot_repr

[[50, 84, 188, 39, 50, 15, 195, 179, 153, 94, 133, 50, 133],
 [168, 29, 8, 42, 155, 152, 172, 58, 34, 1],
 [46, 135, 157, 136, 184, 136, 34, 25, 184, 108, 153, 50, 120],
 [50, 66, 102, 153, 186, 175, 179, 52, 169, 120, 50, 137, 120],
 [10, 79, 134, 131, 55, 175, 79, 68, 76, 123, 34, 63],
 [75, 153, 50, 26, 79, 92, 99, 34, 174, 51, 169, 123, 162],
 [179, 155, 74, 34, 65, 79, 84, 65, 104, 98, 34, 69, 64],
 [6, 8, 185, 153, 136, 50, 109, 40, 136, 34, 19],
 [72, 8, 175, 120, 21, 108, 34, 137, 141],
 [50, 153, 28, 153, 106, 42, 101, 34, 187, 11]]

In [26]:
sentence_length=15
embedded_layer=pad_sequences(one_hot_repr,padding='post',maxlen=sentence_length)
print(embedded_layer)

[[ 50  84 188  39  50  15 195 179 153  94 133  50 133   0   0]
 [168  29   8  42 155 152 172  58  34   1   0   0   0   0   0]
 [ 46 135 157 136 184 136  34  25 184 108 153  50 120   0   0]
 [ 50  66 102 153 186 175 179  52 169 120  50 137 120   0   0]
 [ 10  79 134 131  55 175  79  68  76 123  34  63   0   0   0]
 [ 75 153  50  26  79  92  99  34 174  51 169 123 162   0   0]
 [179 155  74  34  65  79  84  65 104  98  34  69  64   0   0]
 [  6   8 185 153 136  50 109  40 136  34  19   0   0   0   0]
 [ 72   8 175 120  21 108  34 137 141   0   0   0   0   0   0]
 [ 50 153  28 153 106  42 101  34 187  11   0   0   0   0   0]]


In [27]:
## feature representation
dimensions=20

In [68]:
model=Sequential()
model.add(Embedding(vocab_size,dimensions,input_shape=(15,)))
keras.layers.Flatten()
model.add(Dense(64, activation='relu'))  # Add a dense layer
model.add(Dense(1))  # Output layer for binary classification (example)
model.compile(optimizer='adam', loss="mean_squared_error", metrics=['mse'])  # Adjust loss function as needed


c:\ProgramData\Anaconda11\Lib\site-packages\keras\src\layers\core\embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [69]:
model.summary()

Model: "sequential_25"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_25 (Embedding)        │ (None, 15, 20)         │         4,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_52 (Dense)                │ (None, 15, 64)         │         1,344 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_53 (Dense)                │ (None, 15, 1)          │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,409 (21.13 KB)

 Trainable params: 5,409 (21.13 KB)

 Non-trainable params: 0 (0.00 B)

In [70]:
model.predict(embedded_layer)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step


array([[[ 3.3375811e-02],
        [-9.3267057e-03],
        [-2.0650139e-02],
        [-5.7938807e-03],
        [ 3.3375811e-02],
        [-2.4076354e-02],
        [-1.1863422e-02],
        [-1.1244783e-02],
        [ 1.0093279e-02],
        [ 2.6340422e-03],
        [-7.7779852e-03],
        [ 3.3375811e-02],
        [-7.7779852e-03],
        [-1.8954536e-02],
        [-1.8954536e-02]],

       [[ 2.5637182e-03],
        [ 5.7988986e-03],
        [-1.1419291e-02],
        [-7.2950409e-03],
        [-8.2825758e-03],
        [-3.7822491e-03],
        [-1.3879683e-02],
        [-1.4522405e-02],
        [-6.5041604e-03],
        [ 5.3836741e-03],
        [-1.8954536e-02],
        [-1.8954536e-02],
        [-1.8954536e-02],
        [-1.8954536e-02],
        [-1.8954536e-02]],

       [[-6.5484047e-03],
        [ 4.7370405e-03],
        [ 2.4427388e-02],
        [ 1.6274422e-02],
        [-1.7062951e-02],
        [ 1.6274422e-02],
        [-6.5041604e-03],
        [ 1.3122034e-02],
        

In [71]:
embedded_layer[0]

array([ 50,  84, 188,  39,  50,  15, 195, 179, 153,  94, 133,  50, 133,
         0,   0])